name: Screenshot Workflow

on: [push]

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Playwright
        run: |
          npm install -D playwright
          npx playwright install  # Adicionado para instalar os navegadores

      - name: Run Screenshot Script
        run: |
          echo "const { chromium } = require('playwright');" > screenshot.js
          echo "const fs = require('fs');" >> screenshot.js
          echo "const path = require('path');" >> screenshot.js
          echo "(async () => {" >> screenshot.js
          echo "    console.log('[INFO] Iniciando o script de automação.');" >> screenshot.js
          echo "    const browser = await chromium.launch({ headless: false });" >> screenshot.js
          echo "    const context = await browser.newContext();" >> screenshot.js
          echo "    try {" >> screenshot.js
          echo "        const cookiesPath = path.resolve(__dirname, 'cookies.json');" >> screenshot.js
          echo "        const cookies = JSON.parse(fs.readFileSync(cookiesPath, 'utf-8'));" >> screenshot.js
          echo "        await context.addCookies(cookies);" >> screenshot.js
          echo "        console.log('[INFO] Cookies carregados e aplicados com sucesso.');" >> screenshot.js
          echo "    } catch (error) {" >> screenshot.js
          echo "        console.error('[ERROR] Erro ao carregar cookies:', error);" >> screenshot.js
          echo "        await browser.close();" >> screenshot.js
          echo "        process.exit(1);" >> screenshot.js
          echo "    }" >> screenshot.js
          echo "    const page = await context.newPage();" >> screenshot.js
          echo "    try {" >> screenshot.js
          echo "        console.log('[INFO] Navegando para a URL do vídeo...');" >> screenshot.js
          echo "        await page.goto('https://www.tiktok.com/@stuckkonearth/video/7401193456355282219', { timeout: 100000, waitUntil: 'networkidle' });" >> screenshot.js
          echo "        console.log('[INFO] Página do vídeo acessada com sucesso.');" >> screenshot.js
          echo "        await page.screenshot({ path: 'screenshot.png' });" >> screenshot.js
          echo "        console.log('[INFO] Captura de tela salva como screenshot.png');" >> screenshot.js
          echo "    } catch (error) {" >> screenshot.js
          echo "        console.error('[ERROR] Erro ao acessar a página:', error);" >> screenshot.js
          echo "        await browser.close();" >> screenshot.js
          echo "        process.exit(1);" >> screenshot.js
          echo "    }" >> screenshot.js
          echo "    await page.waitForTimeout(120000);" >> screenshot.js
          echo "    await browser.close();" >> screenshot.js
          echo "})();" >> screenshot.js

      - name: Upload Screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: screenshot.png
