name: Playwright Automation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install -y ngrok

      - name: Instalar servidor SSH
        run: sudo apt-get install -y openssh-server

      - name: Criar usuário com permissões root
        run: |
          sudo useradd -m -s /bin/bash myuser  # Cria o usuário
          echo 'myuser:password' | sudo chpasswd  # Define a senha
          sudo usermod -aG sudo myuser  # Adiciona o usuário ao grupo sudo
          echo 'myuser ALL=(ALL) NOPASSWD:ALL' | sudo tee /etc/sudoers.d/myuser  # Concede sudo sem senha

      - name: Configurar servidor SSH
        run: |
          sudo service ssh start
          echo "Servidor SSH iniciado."

      - name: Configurar ngrok com Authtoken
        run: |
          ngrok config add-authtoken ${{ secrets.NGROK_AUTHTOKEN }}  # Certifique-se de que o segredo esteja corretamente configurado

      - name: Iniciar ngrok para SSH
        run: |
          ngrok tcp 22 --log=stdout > ngrok.log &
          sleep 10  # Espera para garantir que o ngrok tenha tempo de iniciar

      - name: Exibir URL do ngrok
        run: |
          echo "Aguardando ngrok iniciar..."
          sleep 5  # Espera adicional para garantir que o ngrok esteja pronto
          if grep -q 'tcp://' ngrok.log; then
            echo "URL do ngrok:"
            cat ngrok.log | grep -o 'tcp://[^ ]*'
          else
            echo "Erro: ngrok não iniciou corretamente."
            cat ngrok.log
            exit 1
          fi

      - name: Manter o Workflow Ativo
        run: |
          echo "Mantendo o workflow ativo. Conecte-se via SSH."
          tail -f /dev/null  # Mantém o processo ativo até que o workflow termine
