name: Screenshot Workflow

on: [push]

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Playwright
        run: |
          npm install -D playwright

      - name: Run Screenshot Script
        run: |
          echo "const { chromium } = require('playwright');" > screenshot.js
          echo "async function run() {" >> screenshot.js
          echo "  const browser = await chromium.launch(); const page = await browser.newPage();" >> screenshot.js
          echo "  await page.goto('https://example.com');" >> screenshot.js
          echo "  await page.screenshot({ path: 'screenshot.png' });" >> screenshot.js
          echo "  await browser.close();" >> screenshot.js
          echo "}" >> screenshot.js
          echo "run();" >> screenshot.js
          node screenshot.js

      - name: Upload Screenshot
        uses: actions/upload-artifact@v2
        with:
          name: screenshot
          path: screenshot.png
